package model;

import java.time.LocalDate;
import java.util.List;

import controller.IStockData;

/**
 * this class Strategy interface defines methods for applying investment strategies.
 * this implementation of this interface provides logic for generating transactions.
 * based on specific investment strategies.
 */
public interface Strategy {

  /**
   * Applies investment strategy to generate transactions.
   * @param date      current date.
   * @param schedule  schedule for executing the investment strategy.
   * @param api      interface for accessing stock data.
   * @return list of transactions generated by applying the strategy.
   */
  List<Transaction> applyStrategy(LocalDate date, Schedule schedule, IStockData api);
}
